# Automatically generated by: ros2nix --flake
{ lib, buildRosPackage, ament-cmake, ament-lint-auto, ament-lint-common, fmt, image-transport, libcarla-client, libjpeg, libpng, rclcpp, tf2, tf2-ros }:
buildRosPackage rec {
  pname = "carla-camera-publisher";
  version = "0.0.0";

  src = lib.sourceByRegex ./. [".*\.[ch]pp$" "^CMakeLists.txt$" "package.xml"];

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake fmt libcarla-client libjpeg libpng tf2 tf2-ros ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ image-transport rclcpp ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Publish camera images from CARLA via ROS image transport";
    license = with lib.licenses; [ mit ];
  };
}
